#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/iperf3

start_service() {
	local enabled port bind

	config_load iperf3
	config_get_bool enabled settings enabled 0
	config_get port settings port 5201
	config_get bind settings bind

	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" -s -p "$port"

	[ -n "$bind" ] && procd_append_param command -B "$bind"

	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger iperf3
}
